EVAL_EXP = 'EVAL_EXP'

EVAL_NUM = 'EVAL_NUM'

EVAL_VAR = 'EVAL_VAR'

EVAL_QUOTE = 'EVAL_QUOTE'

EVAL_QUASIQUOTE = 'EVAL_QUASIQUOTE'
QUASIQUOTE_LOOP = 'QUASIQUOTE_LOOP'

EVAL_LAMBDA = 'EVAL_LAMBDA'

EVAL_DEF = 'EVAL_DEF'
DID_DEF_VAL = 'DID_DEF_VAL'

EVAL_ASS = 'EVAL_ASS'
DID_ASS_VAL = 'DID_ASS_VAL'

EVAL_IF = 'EVAL_IF'
IF_DECIDE = 'IF_DECIDE'
IF_THEN = 'IF_THEN'
IF_ELSE = 'IF_ELSE'

EVAL_BEGIN = 'EVAL_BEGIN'

EVAL_FUNC = 'EVAL_FUNC'
DID_FUNC = 'DID_FUNC'
SIMPLE_FUNC = 'SIMPLE_FUNC'
CHECK_NO_ARGS = 'CHECK_NO_ARGS'
ARG_LOOP = 'ARG_LOOP'
ACC_ARG = 'ACC_ARG'
LAST_ARG = 'LAST_ARG'
DID_LAST_ARG = 'DID_LAST_ARG'
COMPOUND_ARG = 'COMPOUND_ARG'
SIMPLE_ARG = 'SIMPLE_ARG'
DID_SIMPLE_ARG = 'DID_SIMPLE_ARG'
RESTORE_FUNC = 'RESTORE_FUNC'

APPLY_FUNC = 'APPLY_FUNC'

APPLY_PRIMITIVE = 'APPLY_PRIMITIVE'
APPLY_COMPOUND = 'APPLY_COMPOUND'

EVAL_SEQ = 'EVAL_SEQ'
EVAL_SEQ_CONT = 'EVAL_SEQ_CONT'
EVAL_SEQ_LAST = 'EVAL_SEQ_LAST'

ALT_EVAL_SEQ = 'ALT_EVAL_SEQ'
ALT_EVAL_SEQ_CONT = 'ALT_EVAL_SEQ_CONT'
ALT_EVAL_SEQ_END = 'ALT_EVAL_SEQ_END'

DONE = 'DONE'
