EVAL_EXP = 'EVAL_EXP'

DID_DEF_VAL = 'DID_DEF_VAL'

IF_DECIDE = 'IF_DECIDE'
IF_THEN = 'IF_THEN'
IF_ELSE = 'IF_ELSE'

DID_FUNC = 'DID_FUNC'
CHECK_NO_ARGS = 'CHECK_NO_ARGS'
LAST_ARG = 'LAST_ARG'
ARG_LOOP = 'ARG_LOOP'
ACC_ARG = 'ACC_ARG'

APPLY_FUNC = 'APPLY_FUNC'

APPLY_PRIMITIVE = 'APPLY_PRIMITIVE'
APPLY_COMPOUND = 'APPLY_COMPOUND'

EVAL_SEQ = 'EVAL_SEQ'
EVAL_SEQ_CONT = 'EVAL_SEQ_CONT'
EVAL_SEQ_LAST = 'EVAL_SEQ_LAST'

ALT_EVAL_SEQ = 'ALT_EVAL_SEQ'
ALT_EVAL_SEQ_END = 'ALT_EVAL_SEQ_END'